# Generated by Django 2.2.5 on 2021-06-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210611_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fileUrl',
            field=models.CharField(default='', max_length=500),
        ),
    ]
