# Generated by Django 2.2.5 on 2021-06-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20210617_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='posts',
        ),
    ]
